services:
  mosquitto:
    build: mosquitto
    ports:
      - "1883:1883"
    networks:
      - sensor
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sensor
  bridge:
    build: bridge
    depends_on:
      - rabbitmq
      - mosquitto
    networks:
      - sensor
  api:
    build: api
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
    networks:
      - sensor
  dashboard:
    build: dashboard
    ports:
      - "8001:8001"
    depends_on:
      - api
    links:
      - "api:api"
    networks:
      - sensor
networks:
  sensor:
    name: sensor
    driver: bridge
