# frequency in Hz (cycles/sec): must be float d.d+
frequency: 2.0
# amplitude in m : must be float d.d+
amplitude: 1.0
# sample rate in samples/second : must be float d.d+
rate: 16.0
# log mode : must be boolean true|false
debug: true
# type : sin square triangle sawtooth : must be string
wavetype: "sin"
