# frequency in radians/sec : must be float d.d+
frequency: 5.0
# amplitude in m : must be float d.d+
amplitude: 1.0
# sample rate in Hz : must be float d.d+
rate: 20.0
# log mode : must be boolean true|false
debug: true
# type : sin square triangle sawtooth : must be string
wavetype: "triangle"
